version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: main
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
  server:
    build:
      context: ./server
    restart: always
    environment:
      NODE_ENV: prodction
    ports:
      - 5000:5000
    depends_on:
      - db
#   client:
#     build:
#       context: ./client
